export const MOCK_STATS = {
  total_jobs: 4,
  total_candidates: 47,
  shortlisted: 12,
  pipeline_runs: 8,
  avg_score: 67,
  recent_activity: [
    { date: 'Mon', processed: 8 },
    { date: 'Tue', processed: 12 },
    { date: 'Wed', processed: 5 },
    { date: 'Thu', processed: 19 },
    { date: 'Fri', processed: 3 },
  ]
}

export const MOCK_JOBS = [
  {
    id: 'job-001',
    title: 'Senior Backend Engineer',
    department: 'Engineering',
    status: 'active',
    created_at: '2024-08-01',
    candidate_count: 18,
    shortlisted_count: 5,
    requirements: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'AWS'],
    experience: '4-7 years',
    location: 'Remote',
    description: 'Build scalable backend services for our data platform...'
  },
  {
    id: 'job-002',
    title: 'ML Engineer',
    department: 'AI/ML',
    status: 'active',
    created_at: '2024-08-05',
    candidate_count: 11,
    shortlisted_count: 3,
    requirements: ['Python', 'PyTorch', 'LangChain', 'MLflow', 'Kubernetes'],
    experience: '3-6 years',
    location: 'Hybrid',
    description: 'Design and deploy ML pipelines at scale...'
  },
  {
    id: 'job-003',
    title: 'React Frontend Developer',
    department: 'Engineering',
    status: 'closed',
    created_at: '2024-07-15',
    candidate_count: 23,
    shortlisted_count: 6,
    requirements: ['React', 'TypeScript', 'Tailwind', 'GraphQL'],
    experience: '2-5 years',
    location: 'On-site',
    description: 'Build our customer-facing product interface...'
  },
  {
    id: 'job-004',
    title: 'DevOps / Platform Engineer',
    department: 'Infrastructure',
    status: 'active',
    created_at: '2024-08-10',
    candidate_count: 7,
    shortlisted_count: 0,
    requirements: ['Kubernetes', 'Terraform', 'CI/CD', 'Linux', 'Prometheus'],
    experience: '3-6 years',
    location: 'Remote',
    description: 'Own and evolve our cloud infrastructure...'
  },
]

export const MOCK_CANDIDATES = [
  {
    id: 'cand-001',
    name: 'Arjun Mehta',
    filename: 'arjun_mehta_resume.pdf',
    job_id: 'job-001',
    status: 'shortlisted',
    overall_score: 87,
    scores: {
      skills_match: 90,
      experience_match: 85,
      education: 78,
      domain_relevance: 92,
      culture_fit: 80,
    },
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Redis', 'Kafka'],
    experience_years: 5,
    current_role: 'Backend Engineer at Zomato',
    education: 'B.Tech CS — IIT Bombay',
    summary: 'Strong backend profile with 5 years in high-scale systems. Excellent FastAPI and PostgreSQL coverage. Missing AWS experience but compensated by GCP depth.',
    gaps: ['AWS (uses GCP)', 'No Kubernetes mentioned'],
    strengths: ['FastAPI expert', 'PostgreSQL tuning', 'Redis caching', 'High-traffic systems'],
  },
  {
    id: 'cand-002',
    name: 'Priya Sharma',
    filename: 'priya_sharma_cv.pdf',
    job_id: 'job-001',
    status: 'shortlisted',
    overall_score: 81,
    scores: {
      skills_match: 83,
      experience_match: 80,
      education: 75,
      domain_relevance: 85,
      culture_fit: 82,
    },
    skills: ['Python', 'Django', 'FastAPI', 'MySQL', 'AWS', 'Docker'],
    experience_years: 4,
    current_role: 'Software Engineer at Infosys',
    education: 'M.Tech CS — NIT Surat',
    summary: 'Solid backend dev with AWS certification. FastAPI + Docker stack matches well. MySQL instead of PostgreSQL is a minor gap.',
    gaps: ['PostgreSQL (uses MySQL)', 'Limited microservices experience'],
    strengths: ['AWS certified', 'FastAPI', 'Docker', 'REST API design'],
  },
  {
    id: 'cand-003',
    name: 'Rohan Verma',
    filename: 'rohan_verma.pdf',
    job_id: 'job-001',
    status: 'rejected',
    overall_score: 42,
    scores: {
      skills_match: 38,
      experience_match: 45,
      education: 60,
      domain_relevance: 35,
      culture_fit: 50,
    },
    skills: ['Java', 'Spring Boot', 'Oracle DB', 'Maven'],
    experience_years: 2,
    current_role: 'Junior Developer at TCS',
    education: 'B.E. — VJTI Mumbai',
    summary: 'Java-centric profile with no Python or FastAPI experience. Under-qualified in experience band for this role.',
    gaps: ['Python (uses Java)', 'No FastAPI', 'No Docker', 'Under-experienced'],
    strengths: ['Spring Boot', 'OOP fundamentals'],
  },
  {
    id: 'cand-004',
    name: 'Sneha Patel',
    filename: 'sneha_patel_resume.pdf',
    job_id: 'job-001',
    status: 'pending',
    overall_score: 63,
    scores: {
      skills_match: 65,
      experience_match: 62,
      education: 72,
      domain_relevance: 58,
      culture_fit: 60,
    },
    skills: ['Python', 'Flask', 'MongoDB', 'Docker', 'REST APIs'],
    experience_years: 3,
    current_role: 'Full Stack Developer at Startup',
    education: 'B.Tech — DAIICT Gandhinagar',
    summary: 'Good Python foundation but Flask-focused rather than FastAPI. MongoDB instead of PostgreSQL. Potential for growth.',
    gaps: ['FastAPI (uses Flask)', 'PostgreSQL (uses MongoDB)', 'AWS missing'],
    strengths: ['Python', 'Docker', 'REST API design', 'MongoDB'],
  },
]

export const MOCK_PIPELINE_RUNS = [
  {
    id: 'run-001',
    job_id: 'job-001',
    job_title: 'Senior Backend Engineer',
    status: 'completed',
    folder_path: '/resumes/backend_batch_aug',
    total_resumes: 18,
    processed: 18,
    shortlisted: 5,
    started_at: '2024-08-12 10:30',
    completed_at: '2024-08-12 10:34',
  },
  {
    id: 'run-002',
    job_id: 'job-002',
    job_title: 'ML Engineer',
    status: 'completed',
    folder_path: '/resumes/ml_batch_aug',
    total_resumes: 11,
    processed: 11,
    shortlisted: 3,
    started_at: '2024-08-13 14:00',
    completed_at: '2024-08-13 14:03',
  },
]
